version: "2"
services:
  mockServer:
    image: node
    container_name: "im-monorepo"
    restart: always
    volumes:
      - ./:/app/
    working_dir: /app
    entrypoint: /app/dockerEntrypoint.sh
    ports:
      - 5888:5174
